name: Publish to Test PyPI

on: push

jobs:
    build:
        name: Build distribution
        runs-on: ubuntu-latest

        steps:
            # Download the repository into the CI runner
            # Then, install and activate the newest Python 3 release
            - uses: actions/checkout@v4
            - name: set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.x"
            - name: Install pypa/build
              run: python3 -m pip install build --user
            # Build the dists from source and store them
            - name: Build a binary wheel and a source tarball
              run: python3 -m build
            - name: Store the distribution packages
              uses: actions/upload-artifact@v4
              with:
                name: python-package-distributions
                path: dist/
    
    publish-to-testpypi:
        name: Publish distribution to TestPyPI
        needs:
            - build
        runs-on: ubuntu-latest

        environment:
            name: production
            url: https://test.pypi.org/p/tuya-vacuum/

        permissions:
            id-token: write # IMPORTANT: mandatory for trusted publishing

        steps:
            - name: Download the distribution packages
              uses: actions/download-artifact@v4
              with:
                name: python-package-distributions
                path: dist/
            - name: Publish distribution to TestPyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://test.pypi.org/legacy/
        