name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Download the repository into the CI runner
      # Then, install and activate the newest Python 3 release
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact verison of a Python version
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Test with pytest and pytest-cov
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html